name: Doxygen

on:
  workflow_run:
    workflows:
      - CMake
    branches:
      - master
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate document using Doxygen
        run: doxygen

      - name: Git commit & push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -f docs/
          git commit --author=. -m "[Update] (automated) document"
          git push
