name: Doxygen

on:
  workflow_run:
    workflows:
      - CMake
    branches:
      - master
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mattnotmitt/doxygen-action@v1.9.4

      - name: Git commit & push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -f docs/
          git commit --author=. -m "[Update] (automated) document"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
